language: go
  go:
    - "1.9.x"
    - master

os:
  - linux

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9ef17136-8de4-4207-9c02-2aae36ed2131