language: go
  go:
    - "1.9.x"
    - master

os:
  - linux

sudo: false

install:
  - go get -t github.com/mohamedmahmoud97/Zuper-UDP
  - go get -t github.com/vmihailenco/msgpack

script:
  - go run examples/server/server.go
  - go run examples/client/client.go

before_install:
  - cp .netrc ~
  - chmod 600 .netrc