language: go
  go:
    - "1.9.x"
    - master

os:
  - linux

sudo: false

install:
  - go get -t github.com/mohamedmahmoud97/Zuper-UDP
  - go get -t github.com/vmihailenco/msgpack

script:
  - go vet ./...
  - go build -v ./...
  - go install -v
  - examples/server/server
  - examples/client/client

before_install:
  - cp .netrc ~
  - chmod 600 .netrc